secuencial:
	gcc -o MPIseq entregaMPISecuencial.c -Wall -Wextra -Wno-unknown-pragmas
ejerciciouno:
	mpicc -o MPI entregaMPI.c -Wall -Wextra -Wno-unknown-pragmas
ejerciciodos:
	mpicc -o MPIOpm entregaMPI.c -Wall -Wextra -fopenmp