mpi:
	mpicc -o MPI entregaMPI.c -Wall -Wextra -Wno-unknown-pragmas

openmp:
	mpicc -o MPIOpm entregaMPI.c -Wall -Wextra -fopenmp
	
seq:
	gcc -o MPIseq entregaMPISecuencial.c -Wall -Wextra -Wno-unknown-pragmas